---
title: "JS - Async(2) - Promise"
categories: 
  - JavaScript
tags:
  - js
  - async
  - promise
toc: true
toc_sticky: true
toc_label: "주요 목차"
---

## 1. Promise는 뭘끼?
> Promise 는 JS에서 비동기를 간편하게 처리할 수 있게 하는 객체입니다.  
정상적으로 기능이 수행되었다면 성공의 메세지와 함께 처리된 결과값을 전달해줍니다.  
만약 기능에 예상치 못한 문제가 발생하였다면 Error를 전달해주죠.

## 2. Create Promise(Producer)
```js
const promise = new Promise((resolve, reject) => {
    // doing some heavy work (network, read files)
    setTimeout(() => {
        resolve('kwHong');
    }, 2000)
});
```
**Promise**는 성공했을 시 수행하는 **resolve**와 문제가 생겼을 시 수행하는 **reject** 두 가지를 전달합니다. 여기서 유의할 점은 Promise가 생성될 떄마다 자동으로 내부 실행자가 실행이 되는데요. 이러면 사용자가 원하지 않는 시점에서도 실행되어 비효율적인 상황이 발생하죠. 그래서 네트워크와의 통신, 파일 불러오기 같은 무거운 작업들은 비동기 형식 즉, 사용자가 원할 때 실행하는 것이 효율적입니다.

## 3. Using Promise(Consumers)
```js
const promise = new Promise((resolve, reject) => {
    // doing some heavy work (network, read files)
    console.log('doing something');
    setTimeout(() => {
        // resolve('kwHong');
        reject(new Error('no network'));
    }, 2000)
});

promise
    .then(value => {
        console.log(value);
    })
    .catch(error => {
    console.log(error); // Error: no network
    })
    .finally(() => {
        console.log('끝!') // 끝!
    });
```
이번엔 **reject**를 수행하는 Promise로 강제해서 만들었습니다.  
위처럼 promise는 **then**과 **catch**로 성공시 호출, 에러시 호출로 두가지를 호출을 다룰 수 있습니다. 그리고 비교적 최근에 추가된 **finally**는 성공이든 실패든 마지막에 꼭 출력되는 기능을 수행합니다.

## 4. Promise Chainning 
```js
const fetchData = new Promise((resolve, reject) => {
    setTimeout(() => resolve('Data'), 1000);
});

fetchData
    .then(data => data + 'is')
    .then(data => data + 'Empty')
    .then(data => {
        return new Promise((resolve, reject) => {
            setTimeout(() => resolve(data + '😅'), 1000);
        });
    })
    .then(data => console.log(data)); // DataisEmpty😅
```
**Promise Channing**이란 Promise를 호출하고 또 다시 Promise를 묶어서 사용하는 것을 의미합니다. 비동기적인 함수들을 묶어서 사용할 수 있는 큰 장점을 가지고 있습니다.

## 5. Let's take care of the errors.
```js
const getHen = () =>
    new Promise((res, rej) => {
        setTimeout(() => res(`🐔`), 1000);
    });
const getEgg = hen =>
    new Promise((res, rej) => {
        setTimeout(() => res(`${hen} => 🥚`), 1000);
    });
const cook = egg =>
    new Promise((res, rej) => {
        setTimeout(() => res(`${egg} => 🍳`), 1000);
    });

getHen()
    .then(getEgg)
    .then(cook) 
    .then(console.log); // 🐔 => 🥚 => 🍳
```
재밌는 예제를 하나 살펴보죠 :)
계란 후라이를 만드는 과정이고 **then**을 통해서 **Promise** 객체를 꼬리물기 형식으로 표현했습니다. JS에서는 `(hen) => getEgg(hen)` 이 표현식을 `getEgg`로 줄여서 표현할 수 있습니다. 
```js
const getHen = () =>
    new Promise((res, rej) => {
        setTimeout(() => res(`🐔`), 1000);
    });
const getEgg = hen =>
    new Promise((res, rej) => {
        setTimeout(() => rej(new Error(`Hen is Male..`)), 1000);
    });
const cook = egg =>
    new Promise((res, rej) => {
        setTimeout(() => res(`${egg} => 🍳`), 1000);
    });

getHen()
    .then(getEgg)
    .then(cook)
    .then(console.log)
    .catch(console.log); // Error: Hen is Male..
```
에러를 `getEgg`에서 강제로 호출하여 **catch**로 콘솔에 출력하였습니다.
이런식으로 사용자에게 **Promise**를 통해서 알려주는 것이 중요합니다.

```js
getHen()
    .then(getEgg)
    .then(cook)
    .catch(err => {
    return '🍞';
    })
    .then(console.log)
    .catch(console.log); // 🍞
```
또한 **catch**를 추가해서 대체 호출 값을 설정 할수도 있습니다.

## 6. Callback Hell💩 => Promise⭐️
```js
class UserStorage {
    loginUser() {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                if (
                    (id === 'kwHong' && pwd === '123123') ||
                    (id === 'shKim' && pwd === '456456')
                ) {
                    resolve(id);
                } else {
                    reject(new Error('User not found'));
                }
            }, 2000);
        });
    }
    getRoles(user) {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                if (user === 'kwHong') {
                    resolve({ name: 'kwHong', role: 'admin' });
                } else {
                    reject(new Error('No access'));
                }
            }, 1000);
        })
    }
}
```
먼저 Calss를 **Promise**를 활용해서 변형하였습니다.  
그로 인해서 onSuccess, onError를 간단하게 resolve, reject 로 바뀌고 따로 매개변수에 넣지 않아도 됩니다 :)

```js
const userStorage = new UserStorage();
const id = prompt('Input your ID');
const pwd = prompt('Input your Password');

userStorage.loginUser(id, pwd)
    .then(userStorage.getRoles)
    .then(user=> alert(`Hello, ${user.name}! your role is ${user.role}`))
    .catch(alert);
```
엄청난 변화가 느껴지시나요? :)  
**then**과 **catch**로 간단하게 콜백함수의 더러운(?) 로직이 간단하게 바뀌었습니다.  
